### ISSUE TITLE
Visitable Pattern RecyclerView

### ISSUE THREAD

**Issue by pandubaraja** [PatilShreyas/Foodium#11]
Hi @PatilShreyas how about we improve the `PostListAdapter` with **Visitable Pattern**? So we can add view items more dynamically in the app and create the factory for the ViewHolders. 

And also I think `setPosts` function in `PostListAdapter` should not use `notifyDataSetChanged` to update the list, if we use that the `DiffUtil.ItemCallback` will become useless because the adapter will re-render the all items which resulted in blinking page. 

Instead we could use `submitList(items)` provided by `ListAdapter` that `PostListAdapter` extends to only re-render the items which data have changed with the correct animation. 

Thank you 🙏 

Ref: https://proandroiddev.com/writing-better-adapters-1b09758407d2

**Comment by PatilShreyas** [comment]
Thanks for this issue. I'll make required changes soon.

**Comment by pandubaraja** [comment]
Your welcome. Btw can I make a PR for it too?

**Comment by PatilShreyas** [comment]
@pandubaraja Thanks for thinking about contributing. Just fixed this in latest commit. Thank you for this issue and letting me know about it. If there are any other problems, you can fix them too. So, I'm closing this issue.
