### ISSUE TITLE
.idea and apk folders should be ignored by git

### ISSUE THREAD

**Issue by pandubaraja** [PatilShreyas/Foodium#12]
It seems `.idea` folder not ignored by `git` we need to add it to `.gitignore`.
Because it will always changes every time we open Android Studio. 
It's should be ignored because we don't want to add changes that we are not making. 

e.g. misc.xml
![Screen Shot 2020-03-25 at 12 56 24](https://user-images.githubusercontent.com/30037407/77506649-e425fa80-6e98-11ea-8000-9c65fe61e667.png)

And also `apk` should not be in repo because if we build it again it will detect it as change. It is unnecessary to put `apk` in git repo. This will make repo size bigger to clone because we need to download the `apk` too.

![Screen Shot 2020-03-25 at 13 07 34](https://user-images.githubusercontent.com/30037407/77506964-c60cca00-6e99-11ea-8c77-9763fcba36e7.png)

**Comment by pandubaraja** [comment]
Please check this PR https://github.com/PatilShreyas/Foodium/pull/13

Thank you! 🙏

**Comment by PatilShreyas** [comment]
Hi @pandubaraja, Thanks for this. But APK isn't built automatically. So, you'll not face any problem due to `/apk` directory. APK is necessary so anyone can directly install app and it'll be easy to understand repository.
