### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by theapache64** [PatilShreyas/Foodium#16]
First of all, awesome repository. Got a lot to learn in it. :smiley: 

I've a doubt in your code.

Here, https://github.com/PatilShreyas/Foodium/blob/75e4541908c80ae2e4ec3221fb37ffc23ed5b094/app/src/main/java/dev/shreyaspatil/foodium/data/repository/NetworkBoundRepository.kt#L93-L94, 

Why did you marked `fetchFromRemote` with `@MainThread` ? Should it be called from `WorkerThread`? :thinking:

**Comment by PatilShreyas** [comment]
These annotations don't do much. They're like the comment to indicate which thread the function should be called from. This function is already `suspend`. We're running flow on `IO` thread. That's why it doesn't matters too much here.

**Comment by theapache64** [comment]
Yeah, but why it's not @WorkerThrread ?

**Comment by PatilShreyas** [comment]
It's not intentional. Just annotated it with @MainThread as convention (so many repos with same functionality were annotated it with @MainThread)

**Comment by DanteAndroid** [comment]
@PatilShreyas Hi, obviously `suspend fun` should not be annotated with @MainThread. Never heard of this kind of *convention*.

**Comment by PatilShreyas** [comment]
Hi, @theapache64 basically these annotations don't do much, they're like a comment to indicate which thread the function should be called from. This prevents the error of calling a function from other thread. Here, it means this function should be called from the main thread.
