### ISSUE TITLE
[FIX] Changing runBlocking to runBlockingTest in Test

### ISSUE THREAD

**Issue by theapache64** [PatilShreyas/Foodium#17]
https://github.com/PatilShreyas/Foodium/blob/7da456f8361255c5d61ab1f8b4ca9e1008bb6285/app/src/test/java/dev/shreyaspatil/foodium/data/remote/api/FoodiumServiceTest.kt#L77

As you need synchronous execution in `test`, and the recommended way is to call `runBlockingTest` , It should be `runBlockingTest` instead `runBlocking` , right ?

**Comment by PatilShreyas** [comment]
@theapache64 Thanks for noticing this. Yes, you're right it should be `runBlockingTest`.

**Comment by PatilShreyas** [comment]
Thanks @theapache64 for this. I've changed it to `runBlockingTest`.
