### ISSUE TITLE
 NetworkInfo is deprecated

### ISSUE THREAD

**Issue by shamshadpattani** [PatilShreyas/Foodium#19]
NedtworkInfo,activeNetworkInfo and isConnectedOrConnecting are  deprecated in NetWorkUtlits class

**Comment by PatilShreyas** [comment]
Yes, that's why we have used that Listener in that. It'll definitely work.

**Comment by shamshadpattani** [comment]
can you please explain how it work

**Comment by PatilShreyas** [comment]
You can see we've implemented `ConnectivityManager.NetworkCallback` for accessing network state in real-time. As mentioned [here](https://developer.android.com/reference/android/net/NetworkInfo) we've used that. That deprecated method is just used to get current info and we're not fully dependent on that as you can see.

**Comment by shamshadpattani** [comment]
Ok ,Thanks
