### ISSUE TITLE
make details of the dish shareable

### ISSUE THREAD

**Issue by ELTEGANI** [PatilShreyas/Foodium#20]
I want to add the ability to share dish details to social media by providing a button for that.
@PatilShreyas 
@pandubaraja

**Comment by naufalprakoso** [comment]
Hey @ELTEGANI , here I created shareable blog detail at https://github.com/PatilShreyas/Foodium/pull/23

**Comment by ELTEGANI** [comment]
okay cool @naufalprakoso
