### ISSUE TITLE
Allways state is  succesfull

### ISSUE THREAD

**Issue by shamshadpattani** [PatilShreyas/Foodium#24]
Due to this code state always succesfull, 
 ```
 emitAll(fetchFromLocal().map {
            State.success<RESULT>(it)
        })
```

so after internet connection is back,
```
     ```
if (mViewModel.postsLiveData.value is State.Error || mAdapter.itemCount == 0) {
                    getPosts()
                }
```

this block of code does not work...
what i can do fetch new result when immediately the connection is back,

**Comment by PatilShreyas** [comment]
Hi @shamshadpattani, if you turn off internet connectivity and running app for the first time you'll get the error state.

**Comment by shamshadpattani** [comment]
hi @PatilShreyas 
```
if (mViewModel.postsLiveData.value is State.Error || mAdapter.itemCount == 0) {
                    getPosts()
                }
```
this if loop always false..can you please check?

**Comment by PatilShreyas** [comment]
You can try this too. Just clear all data from the app, turn off the connectivity and check, this will surely get executed.

**Comment by shamshadpattani** [comment]
That is ok.but some data is changed when we go to offline when we back to online how it immeditatly show new data?

**Comment by PatilShreyas** [comment]
When connectivity is back again then you can load new posts using a method `getPosts()`. Here it's not used because there's no proper backend for this app.

**Comment by shamshadpattani** [comment]
ok.Thank you
