### ISSUE TITLE
DARK THEME ISSUE

### ISSUE THREAD

**Issue by shamshadpattani** [PatilShreyas/Foodium#25]
I had converted ge the theme in to Dark..Then after reopen the theme again going to white.

**Comment by esQmo** [comment]
This should be related to the default theme your device uses, it's somehow overrides the theme

**Comment by shamshadpattani** [comment]
ya.. i know that .Some users like always Dark them so 
 i solved the issue using shared preference.

**Comment by PatilShreyas** [comment]
Actually this isn't issue at all. Here SharedPreference isn't used. Dark
theme is automatically turned on on specific time.

**Comment by shamshadpattani** [comment]
is dark theme automatically changed?

**Comment by PatilShreyas** [comment]
Yes. See this: https://github.com/PatilShreyas/Foodium/blob/master/app/src/main/java/dev/shreyaspatil/foodium/utils/TimeUtils.kt#L33

and then see this: https://github.com/PatilShreyas/Foodium/blob/master/app/src/main/java/dev/shreyaspatil/foodium/FoodiumApp.kt#L53

**Comment by shamshadpattani** [comment]
ok  thanku
