### ISSUE TITLE
How to use networkBoundRepositroy  with out a offline support(Not a issue, for more knowledge)

### ISSUE THREAD

**Issue by shamshadpattani** [PatilShreyas/Foodium#32]
hai, i follow your code style in my project. so i want to use a api call available only in online.
how it is possible using networkboundRepository

**Comment by PatilShreyas** [comment]
For this, you'll not need a local database. So you can just remove that part. Else, everything will be the same.

**Comment by PatilShreyas** [comment]
Okay. I think you've got a solution. In future, if your intention of the opening issue is same then please use [StackOverflow](https://stackoverflow.com). It's recommended to use it for such purposes.
