### ISSUE TITLE
Wrong APK URL in readme

### ISSUE THREAD

**Issue by amardeshbd** [PatilShreyas/Foodium#33]
The APK download in https://github.com/PatilShreyas/Foodium/blob/master/README.md points to https://github.com/patilshreyas/gitktdroid/releases/latest/download/app.apk which is for https://github.com/patilshreyas/gitktdroid/ repo.

I am guessing this is not intentional?

**Comment by PatilShreyas** [comment]
Thanks for reporting this. Actually maybe it's mistake due to copy paste.

**Comment by PatilShreyas** [comment]
URL to download APK is now fixed. Thanks for this.
