### ISSUE TITLE
Use room suspending functions

### ISSUE THREAD

**Issue by shubham08gupta** [PatilShreyas/Foodium#41]
**Use room inbuilt support for coroutines**
Currently, the code does not use the functionality provided by the Room library. Instead, it uses Dispatchers.IO for threading purposes. I intend to remove this and add inbuilt support.

Proposed changes:
[proposed PR](https://github.com/PatilShreyas/Foodium/compare/master...shubham08gupta:use_room_with_coroutine?expand=1
)

**Comment by PatilShreyas** [comment]
Since it's merged, closing this issue. Thanks!
