### ISSUE TITLE
Implementation using Jetpack Compose

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/Foodium#45]
### Proposed change
- Demo implementation of *Foodium app* using Jetpack compose will be simply awesome.
- This change is encouraged during ***"Hacktoberfest"*** for the participants of this event.

### References
- [Jetpack Compose | Android Developers](https://developer.android.com/jetpack/compose)
- [Jetpack Compose Basiccs](https://codelabs.developers.google.com/codelabs/jetpack-compose-basics/)

**Comment by faogustavo** [comment]
@PatilShreyas do you already have some plan for the migration?

**Comment by PatilShreyas** [comment]
Yeah. We have to keep example of Jetpack compose on separate branch.
