### ISSUE TITLE
Emit Network Response directly without saving the data.

### ISSUE THREAD

**Issue by bibutikoley** [PatilShreyas/Foodium#47]
There will be a scenario in which we won't need to save the data to database and use values directly from the network.
Can you share a similar version of `NetworkBoundRepository` to perform the same.
<img width="1440" alt="Screen Shot 2020-10-28 at 7 44 08 PM" src="https://user-images.githubusercontent.com/20051993/97448596-d5378700-1956-11eb-8603-b17916aad7f2.png">

**Comment by PatilShreyas** [comment]
Can you describe?

**Comment by bibutikoley** [comment]
I simply want to emit flow of type `State` with network response from Repository without saving the response to db.

In current code what modifications are need to do the same?

**Comment by PatilShreyas** [comment]
But we're assuming local storage _(Room DB)_ as a single source of truth. So it's recommended if we keep it as it is.
