### ISSUE TITLE
Use the Android Sharesheet for a more modern looking share tray

### ISSUE THREAD

**Issue by meets7** [PatilShreyas/Foodium#48]
**Describe the bug/request**
Use the Android Sharesheet to provide the share functionality, allowing for a more modern looking share menu on Android 10 (API level 29) and above. This will also add the ability to show rich content to previews.

So the UI for the share tray could something like this post this change:

<img src="https://user-images.githubusercontent.com/6688825/100489972-65472880-30dd-11eb-8d76-28069b1a23c4.png" height=300 width=150>

**Additional context**
Essentially, the following change will be done:

> For all types of sharing, create an intent and set its action to Intent.ACTION_SEND. In order to display the Android Sharesheet you need to call Intent.createChooser() , passing it your Intent object. It returns a version of your intent that will always display the Android Sharesheet.

Source: [link](https://developer.android.com/training/sharing/send#using-android-system-sharesheet)

**Comment by PatilShreyas** [comment]
@meets7 Awesome, would you like to work on that?

**Comment by meets7** [comment]
Sure.
