### ISSUE TITLE
Running dao tests runs forever

### ISSUE THREAD

**Issue by raghunandankavi2010** [PatilShreyas/Foodium#58]
While running tests for PostsDaoTest the tests keeps running without completing. But if i test with normal flow builder emitting item and asserting inside run blocking it completes and tests pass.

        val flow =  flow {
            emit(1)
        }

        assertThat(1, equalTo(flow.first()))

The above works inside runBlocking.

I found nothing similar to this issue on internet. Running on latest android studio. Am i missing anything

![1](https://user-images.githubusercontent.com/4216745/105130015-4167f800-5b0c-11eb-9d9e-1f4f49242d56.png)

**Comment by PatilShreyas** [comment]
Thanks for reporting this @raghunandankavi2010. I guess something missed from last many commits. Need to look into it.

**Comment by raghunandankavi2010** [comment]
Ok. I tried with other git repos. Seemsi can replciate this issue with other repos as well. So is this something only i am facing?

**Comment by PatilShreyas** [comment]
Would you like to contribute?

**Comment by raghunandankavi2010** [comment]
I am still unsure if its the right way. According to the docs https://developer.android.com/kotlin/flow/test 'toList()` is used when you fake a repository to provide data and then assertion works. 

I can certainly go ahead and create a PR.
