### ISSUE TITLE
Add More Screens

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/Foodium#6]
Have to add more screens in this app (currently it's single screen app).
- `DetailView` - On Clicking blog of `MainActivity` user should see this screen.

**Comment by esQmo** [comment]
This could be easily implemented if your api permits so. Is there a parameter to pass to the URL to query a specific post's details?

**Comment by PatilShreyas** [comment]
Not as of now. I'll be extending this support soon..
