### ISSUE TITLE
how to build this project in android studio

### ISSUE THREAD

**Issue by UchihaSR** [PatilShreyas/Foodium#67]
**Describe the bug/request**
well, i am new to kotlin and android development. if i opened this project in the android studio how to run it

**Comment by esQmo** [comment]
@UchihaSR You should first learn some basics I guess. Running an application within Android Studio is among the basics. There are thousands and thousands of tutorials on Internet.

**Comment by mwshubham** [comment]
@UchihaSR Please read https://developer.android.com/guide for building the first App. Please create a more specific issue regarding your problem. @PatilShreyas Please review close this due to an incomplete problem statement.

**Comment by PatilShreyas** [comment]
Thanks @mwshubham. Closing it
