### ISSUE TITLE
dev branch missing

### ISSUE THREAD

**Issue by codeteo** [PatilShreyas/Foodium#7]
Hi,

Cool project thanks for sharing.

Just checked Contributions guidelines and you mention `dev` branch but 
I guess you 've forgot to push it ?

EDIT: Unless you meant `master` ?

**Comment by PatilShreyas** [comment]
Currently there's no any dev branch. If anyone is gonna contribute then changes will be merged into dev branch.

**Comment by PatilShreyas** [comment]
Fixed!
