### ISSUE TITLE
Where can I find the API?

### ISSUE THREAD

**Issue by Twenty4marc** [PatilShreyas/Foodium#72]

**Comment by PatilShreyas** [comment]
The link has been there in docs/README.md

**Comment by PatilShreyas** [comment]
It's statically hosted here: https://patilshreyas.github.io/DummyFoodiumApi/api/posts/

**Comment by PatilShreyas** [comment]
Please use [discussions](https://github.com/PatilShreyas/Foodium/discussions) for asking questions/doubts instead of raising an issue
