### ISSUE TITLE
Deprecated JUnit AssertThat()

### ISSUE THREAD

**Issue by RAJATNEGI** [PatilShreyas/Foodium#73]
**Describe the bug/request**
JUnit "**AssertThat**" is deprecated use Google Truth instead of that.

**Additional context**
In FoodiumServiceTest class the JUnit assertThat is used.
Please use google truth instead of this.

**Comment by RAJATNEGI** [comment]
Hi @PatilShreyas i would like to work on this issue

**Comment by PatilShreyas** [comment]
Sure @RAJATNEGI you can raise a PR against master branch

**Comment by RAJATNEGI** [comment]
Hi @PatilShreyas https://github.com/PatilShreyas/Foodium/pull/74 pls review

**Comment by PatilShreyas** [comment]
Thanks @RAJATNEGI
