### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by shubhamshah14102** [PatilShreyas/Foodium#75]
**Describe the bug/request**
Hi @PatilShreyas 
There is  a scope of improvements in the README.md file and i would like to update it .
For eg : "This makes it offline capable 😃." can be replaced with "This allows us to use it offline 😃".
Changes like this will be appealing to the readers and will explain the project in a better manner.
I would like to work on this issue so please can you assign this to me.

**Additional context**

**Comment by PatilShreyas** [comment]
No @shubhamshah14102. This change is not necessary at all. If you have any codebase-related changes then would be happy to review them. Feel free to contribute
