### ISSUE TITLE
Animated splash screen

### ISSUE THREAD

**Issue by PranavVyas20** [PatilShreyas/Foodium#76]
The static logo can be replaced with a small animation. Can I work on this ?

**Comment by PatilShreyas** [comment]
what kind of small animation @PranavVyas20? Remember we don't have to introduce another activity for showing splash

**Comment by PranavVyas20** [comment]
I was thinking about something like this - 
But not sure if this can be done without creating another activity 

https://user-images.githubusercontent.com/90063033/136198135-d2204153-0341-481b-b97b-54fef6efa285.mp4

**Comment by PatilShreyas** [comment]
Sorry @PranavVyas20 but this change is not necessary
