### ISSUE TITLE
Unable to switch back to light theme after switching to dark

### ISSUE THREAD

**Issue by esQmo** [PatilShreyas/Foodium#8]
The button from the menu doesn't seem to switch back to light theme once switched to dark theme

**Comment by PatilShreyas** [comment]
Library doesn't supports Dark theme as of now. Thanks for reminding this.
I'll try to migrate it.

**Comment by esQmo** [comment]
Oh my bad. The button's working fine. After checking the function in the code, I saw in the block below: 
```
val mode =
                    if ((resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK) ==
                        Configuration.UI_MODE_NIGHT_NO
                    ) {
                        AppCompatDelegate.MODE_NIGHT_YES
                    } else {
                        AppCompatDelegate.MODE_NIGHT_AUTO_BATTERY
                    }
```
 **MODE_NIGHT_AUTO_BATTERY** uses dark mode when the system's 'Battery Saver' feature is enabled,my device had that mode on that's why the theme was still dark.
